name: .NET CI/CD Pipeline

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
    secrets:
      github_token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.101'

    # Step 3: Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Step 4: Build the application
    - name: Build
      run: dotnet build
